name          'example42/haproxy'
version '3.0.2'
source        'https://github.com/example42/puppet-haproxy'
author        'Alessandro Franceschi'
license       'Apache License, Version 2.0'
summary       'This module installs and manages haproxy'
description   'This module installs and manages haproxy. Based of stdmod/puppet-skeleton-standard 0.0.3.'
project_page  'http://www.example42.com'
dependency    'puppetlabs/stdlib'
dependency    'example42/stdmod'
